- hosts: windows
  gather_facts: True
  become_method: runas
  vars:
    sql_instance_name: myAppName
    ansible_become_password: MyStrongPassword
  tasks:
    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature
    - name: Reboot if installing Web-Server feature requires it
      win_reboot:
      when: win_feature.reboot_required
    - debug: var=hostvars[inventory_hostname]
    
    - name: create a directory for installer download
      win_file: 
          path: c:\sql19
          state: directory
    - name: create a directory for configuration
      win_file: 
          path: c:\sql_conf
          state: directory
    
    - name: create a directory for installer extraction
      win_file: 
          path: c:\sql19\installer
          state: directory

    - name: create the configuration file
      win_template: 
        src: files/sql_conf.ini.j2
        dest: c:\sql_conf\sql_conf.ini

    - name: a pre requisite of sql net-framework-35
      win_feature:
          name: NET-Framework-Core
          state: present

    - name: check downloaded file exists
      win_stat:
          path: c:\sql19\sql_installer.exe
      register: installer_file

    - name: get the installer
      win_get_url:
            url: 'https://download.microsoft.com/download/7/f/8/7f8a9c43-8c8a-4f7c-9f92-83c18d96b681/SQL2019-SSEI-Expr.exe'
            dest: 'c:\sql19\sql_installer.exe'
      when: not installer_file.stat.exists
    
    - name: Install the database
      win_command: c:\sql19\sql_installer.exe /configurationfile=c:\sql_conf\sql_conf.ini
      args:
        chdir: c:\sql19
      become: yes
      become_user: atif

    - name: Add or update registry for ip port
      win_regedit:
        path: 'HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL15.{{ sql_instance_name }}\MSSQLServer\SuperSocketNetLib\Tcp\IPAll'
        name: TcpPort
        data: 1433
      register: win_reg

    - name: Restart a service
      win_service:
        name: 'MSSQL${{ sql_instance_name }}'
        force_dependent_services: yes
        state: restarted
      when: win_reg.changed